HEROES = {
    1: u'Anti-Mage',
    2: u'Axe',
    3: u'Bane',
    4: u'Bloodseeker',
    5: u'Crystal Maiden',
    6: u'Drow Ranger',
    7: u'Earthshaker',
    8: u'Juggernaut',
    9: u'Mirana',
    10: u'Morphling',
    11: u'Shadow Fiend',
    12: u'Phantom Lancer',
    13: u'Puck',
    14: u'Pudge',
    15: u'Razor',
    16: u'Sand King',
    17: u'Storm Spirit',
    18: u'Sven',
    19: u'Tiny',
    20: u'Vengeful Spirit',
    21: u'Windranger',
    22: u'Zeus',
    23: u'Kunkka',
    25: u'Lina',
    26: u'Lion',
    27: u'Shadow Shaman',
    28: u'Slardar',
    29: u'Tidehunter',
    30: u'Witch Doctor',
    31: u'Lich',
    32: u'Riki',
    33: u'Enigma',
    34: u'Tinker',
    35: u'Sniper',
    36: u'Necrophos',
    37: u'Warlock',
    38: u'Beastmaster',
    39: u'Queen of Pain',
    40: u'Venomancer',
    41: u'Faceless Void',
    42: u'Skeleton King',
    43: u'Death Prophet',
    44: u'Phantom Assassin',
    45: u'Pugna',
    46: u'Templar Assassin',
    47: u'Viper',
    48: u'Luna',
    49: u'Dragon Knight',
    50: u'Dazzle',
    51: u'Clockwerk',
    52: u'Leshrac',
    53: u"Nature's Prophet",
    54: u'Lifestealer',
    55: u'Dark Seer',
    56: u'Clinkz',
    57: u'Omniknight',
    58: u'Enchantress',
    59: u'Huskar',
    60: u'Night Stalker',
    61: u'Broodmother',
    62: u'Bounty Hunter',
    63: u'Weaver',
    64: u'Jakiro',
    65: u'Batrider',
    66: u'Chen',
    67: u'Spectre',
    68: u'Ancient Apparition',
    69: u'Doom',
    70: u'Ursa',
    71: u'Spirit Breaker',
    72: u'Gyrocopter',
    73: u'Alchemist',
    74: u'Invoker',
    75: u'Silencer',
    76: u'Outworld Devourer',
    77: u'Lycanthrope',
    78: u'Brewmaster',
    79: u'Shadow Demon',
    80: u'Lone Druid',
    81: u'Chaos Knight',
    82: u'Meepo',
    83: u'Treant Protector',
    84: u'Ogre Magi',
    85: u'Undying',
    86: u'Rubick',
    87: u'Disruptor',
    88: u'Nyx Assassin',
    89: u'Naga Siren',
    90: u'Keeper of the Light',
    91: u'Wisp',
    92: u'Visage',
    93: u'Slark',
    94: u'Medusa',
    95: u'Troll Warlord',
    96: u'Centaur Warrunner',
    97: u'Magnus',
    98: u'Timbersaw',
    99: u'Bristleback',
    100: u'Tusk',
    101: u'Skywrath Mage',
    102: u'Abaddon',
    103: u'Elder Titan',
    104: u'Legion Commander',
    105: u'Techies',
    106: u'Ember Spirit',
    107: u'Earth Spirit',
    109: u'Terrorblade',
    110: u'Phoenix',
    111: u'Oracle'
}
